# Basic
title: Liang Zhang
subtitle: Move fast, be bold
description: Change takes time
# 头像里面的标题
avatarTitle: John Zhang
# 头像里面的描述
avatarDesc: A interesting guy
url: https://johnbryant.github.io
baseurl: /blog

# Comment
#comment:
    #disqus: leopard
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    #weibo: 5366874726 
    github: johnbryant
    # twitter: 
    mail: johnbryant262@icloud.com

# 百度统计 
# 使用博客模板请去掉或者更换 id 
#baidu:
    #id: 8ba1c6be0953b6f9c2ba38e57f615421  

# Google Analytics
# 使用博客模板请去掉或者更换 id
#ga:
    #id: UA-84134159-3   
    #host: auto  



permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: Homepage

# Navigation buttons in the front page.s
nav:
    - {title: Articles, description: archive, url: '/archive'}   
    - {title: Tags, description: tags, url: '/tags'}      
    - {title: About, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 10
paginate_path: "page/:num/"


